default:
  - .vscode:
    - settings.json
    - launch.json
  - config:
    - config.yaml
  - data:
    - database.db
  - docker:
    - Dockerfile
    - .dockerignore
  - docs
  - lib
  - logs:
    - main.log
  - src:
    - tests:
      - fixtures:
        - __init__.py
      - e2e:
        - __init__.py
    - core:
      - __init__.py
    - utils:
      - __init__.py
      - logger.py
  - tools:
    - __init__.py
  - main.py
  - .coverage
  - .gitattributes
  - .gitignore
  - .flake8
  - pytest.ini
  - README.md
  - requirements.txt
  - __init__.py